package com.fudanmed.platform.core.web.server.service.template;

import com.fudanmed.platform.core.common.proxy.RCFaultLevelProxy;
import com.fudanmed.platform.core.domain.RCRepairTask;
import com.fudanmed.platform.core.domain.proxy.RCOrganizationProxy;
import com.fudanmed.platform.core.web.server.service.project.RepairTaskMapper;
import com.fudanmed.platform.core.web.shared.project.UIRepairTask;
import com.fudanmed.platform.core.web.shared.project.UIRepairTaskStatus;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

@SuppressWarnings("all")
public class EBoardTemplate {
  public static String template(final Collection<RCRepairTask> tasks, final RepairTaskMapper mapper) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table width=\"1024px\" align=\"center\" id=\"Table1\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<td width=\"50px\" height=\"594\" rowspan=\"4\" background=\"images/eboard/bj_left.jpg\" >&nbsp; </TD>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<td width=\"974px\" height=\"73\" align=\"left\" colspan=2><IMG  src=\"images/eboard/logo.jpg\"></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td width=\"974px\" height=\"35\" align=\"center\" background=\"images/eboard/green.jpg\"  valign=\"middle\" colspan=2><FONT color=\"#ffffff\"><B> \u5F53\u524D\u62A5\u4FEE\u9879\u76EE\u5B9E\u65F6\u72B6\u6001</B></FONT></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td width=\"169px\" id =\"left\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<TABLE  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<TD width=\"100%\" height=\"139\" align=\"center\" valign=\"top\"><IMG  ");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("height=\"139\" src=\"images/eboard/left.jpg\"></TD>                ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<TD height=\"9\" width=\"100%\"");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("background=\"images/eboard/bj2.jpg\"></TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("<TD width=\"100%\" height=\"32\" align=\"center\" background=\"images/eboard/bj3.jpg\" ><div  ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("style=\"padding-top: 5px;width:162px;background-image:url(images/eboard/bj_green.jpg);\" ><b>\u91CD\u8981\u901A\u77E5</b></div></TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<TD width=\"100%\" height=\"297\" align=\"center\" id=\"TD1\"  background=\"images/eboard/bj3.jpg\" valign=\"top\" ><div  style=\"padding:5px;align:left;width:95%;text-indent:2em; text-align:left\">\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5\u901A\u77E5</div></TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<TD width=\"100%\" height=\"9\" ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("background=\"images/eboard/bj4.jpg\"></TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</TABLE>                ");
    _builder.newLine();
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("<td width=\"805px\" id =\"right\" style=\"padding-left:5px;\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<TABLE  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<TD width=\"100%\" align=\"center\" height=\"320\" valign=\"top\"><div  style=\"margin:2px\uFF1Balign:left;width:95%;height:95%;text-align:left\">");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<MARQUEE width=\"100%\" height=\"100%\" id=\"typhoon\" ");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("scrolldelay=\"100\" direction=\"up\" scrollamount=\"1\">");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<TABLE width=\"100%\" align=\"center\"  ");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("border=\"0\" cellspacing=\"5\" cellpadding=\"2\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th>\u62A5\u4FEE\u5355\u53F7</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th>\u98CE\u9669\u7B49\u7EA7</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th>\u62A5\u4FEE\u65F6\u95F4</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th>\u62A5\u4FEE\u79D1\u5BA4</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th>\u7EF4\u4FEE\u72B6\u6001</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th>\u62A5\u4FEE\u5185\u5BB9</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tr>");
    _builder.newLine();
    {
      final Function1<RCRepairTask,UIRepairTask> _function = new Function1<RCRepairTask,UIRepairTask>() {
          public UIRepairTask apply(final RCRepairTask it) {
            UIRepairTask _transform = mapper.transform(it);
            return _transform;
          }
        };
      Iterable<UIRepairTask> _map = IterableExtensions.<RCRepairTask, UIRepairTask>map(tasks, _function);
      for(final UIRepairTask task : _map) {
        _builder.append("<TR>");
        _builder.newLine();
        _builder.append("<TD height=\"18\" style=\"border-bottom:#00ff00 dotted thin;text-align:left\">");
        _builder.newLine();
        _builder.append("\t");
        String _reportSid = task.getReportSid();
        _builder.append(_reportSid, "	");
        _builder.newLineIfNotEmpty();
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("<TD height=\"18\" style=\"border-bottom:#00ff00 dotted thin;text-align:left\">");
        _builder.newLine();
        _builder.append("\t");
        RCFaultLevelProxy _faultLevel = task.getFaultLevel();
        String _name = _faultLevel==null?(String)null:_faultLevel.getName();
        _builder.append(_name, "	");
        _builder.newLineIfNotEmpty();
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("<TD height=\"18\" style=\"border-bottom:#00ff00 dotted thin;text-align:left\">");
        _builder.newLine();
        _builder.append("\t");
        SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        Date _reportTime = task.getReportTime();
        String _format = _simpleDateFormat.format(_reportTime);
        _builder.append(_format, "	");
        _builder.newLineIfNotEmpty();
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("<TD height=\"18\" style=\"border-bottom:#00ff00 dotted thin;text-align:left\">");
        _builder.newLine();
        _builder.append("\t");
        RCOrganizationProxy _reportOrg = task.getReportOrg();
        String _name_1 = _reportOrg==null?(String)null:_reportOrg.getName();
        _builder.append(_name_1, "	");
        _builder.newLineIfNotEmpty();
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("<TD height=\"18\" style=\"border-bottom:#00ff00 dotted thin;text-align:left\">");
        _builder.newLine();
        _builder.append("\t");
        UIRepairTaskStatus _status = task.getStatus();
        _builder.append(_status, "	");
        _builder.newLineIfNotEmpty();
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("<TD height=\"18\" style=\"border-bottom:#00ff00 dotted thin;text-align:left\">");
        _builder.newLine();
        _builder.append("\t");
        String _comment = task.getComment();
        _builder.append(_comment, "	");
        _builder.newLineIfNotEmpty();
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("</TR>");
        _builder.newLine();
      }
    }
    _builder.append("                      ");
    _builder.append("</TABLE>");
    _builder.newLine();
    _builder.append("                      ");
    _builder.append("</MARQUEE>");
    _builder.newLine();
    _builder.append("</div></TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<TD width=\"100%\" height=\"139\" align=\"center\" ><IMG  ");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("src=\"images/eboard/ban.jpg\"></TD>                ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</TABLE>     ");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td width=\"924px\" height=\"35\" align=\"left\"  valign=\"middle\" colspan=2><IMG  width=\"549\" height=\"23\" src=\"images/eboard/base.jpg\"></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>\t\t");
    _builder.newLine();
    String _string = _builder.toString();
    return _string;
  }
}
