package com.fudanmed.platform.core.web.server.service.template;

import com.fudanmed.platform.core.common.RCSystemParameter;
import com.fudanmed.platform.core.common.proxy.RCMaterialBrandProxy;
import com.fudanmed.platform.core.domain.RCEmployee;
import com.fudanmed.platform.core.domain.RCSupplier;
import com.fudanmed.platform.core.warehouse.RCInStockRecord;
import com.fudanmed.platform.core.warehouse.RCInStockRecordItem;
import com.fudanmed.platform.core.warehouse.RCInStoreType;
import com.fudanmed.platform.core.warehouse.RCWarehouse;
import com.fudanmed.platform.core.warehouse.proxy.RCProduceSpecificationUnitProxy;
import com.fudanmed.platform.core.web.server.service.warehouse.InStockRecordItemMapper;
import com.fudanmed.platform.core.web.shared.warehouse.UIInStockRecordItem;
import com.google.common.base.Objects;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

@SuppressWarnings("all")
public class InStockTemplate {
  public static String nullsafe(final String s) {
    String _xifexpression = null;
    boolean _equals = Objects.equal(s, null);
    if (_equals) {
      _xifexpression = "&nbsp;";
    } else {
      _xifexpression = s;
    }
    return _xifexpression;
  }
  
  public static String nullsafe(final Double s) {
    String _xifexpression = null;
    boolean _equals = Objects.equal(s, null);
    if (_equals) {
      _xifexpression = "&nbsp;";
    } else {
      String _string = s.toString();
      _xifexpression = _string;
    }
    return _xifexpression;
  }
  
  public static String nullsafe(final Integer s) {
    String _xifexpression = null;
    boolean _equals = Objects.equal(s, null);
    if (_equals) {
      _xifexpression = "&nbsp;";
    } else {
      String _string = s.toString();
      _xifexpression = _string;
    }
    return _xifexpression;
  }
  
  public static String template(final RCInStockRecord value, final RCSystemParameter parameter, final InStockRecordItemMapper itemMapper) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<html> ");
    _builder.newLine();
    _builder.append("<head> ");
    _builder.newLine();
    _builder.append("<title>\u5165\u5E93\u5355</title> ");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"> ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("<style> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("table");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("border:0px solid black;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("width:22cm;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("border-spacing:0px 7px;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("td,th{");
    _builder.newLine();
    _builder.append("color:#000000;");
    _builder.newLine();
    _builder.append("font-size: 12pt; ");
    _builder.newLine();
    _builder.append("font-family:Arial,Microsoft YaHei,SimHei,SimSun;");
    _builder.newLine();
    _builder.append("height:0.5cm;");
    _builder.newLine();
    _builder.append("padding-left:2px;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdlabel ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("border-style:none; ");
    _builder.newLine();
    _builder.append("font-weight:bold;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdleft");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:left;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdright");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:right;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdcenter");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdtop ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("vertical-align:top;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.append(".tdbottom ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdcontent");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border-style:none;");
    _builder.newLine();
    _builder.append("border-bottom:1px solid #000000;");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("thead");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("display:table-header-group;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width:22cm;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border-collapse:collapse;");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL th");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-top:3px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-bottom:3px;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL td");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("padding:3px 7px 2px 7px;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("font-size: 10pt;");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("</style> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</head> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<body > ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<h2 style=\"width:21cm;text-align:center;font-family:Arial,Microsoft YaHei,SimHei,SimSun;\" >");
    String _orgName = parameter.getOrgName();
    _builder.append(_orgName, "");
    _builder.append("\u5165\u5E93\u5355</h2>");
    _builder.newLineIfNotEmpty();
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u5165\u5E93\u5355\u53F7:</td>");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdcontent\">");
    String _sid = value.getSid();
    String _nullsafe = InStockTemplate.nullsafe(_sid);
    _builder.append(_nullsafe, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u5165\u5E93\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date _date = value.getDate();
    String _format = _simpleDateFormat.format(_date);
    _builder.append(_format, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u5165\u5E93\u4ED3\u5E93:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"31%\" class=\"tdcontent\">");
    RCWarehouse _store = value.getStore();
    String _entityName = _store.getEntityName();
    String _nullsafe_1 = InStockTemplate.nullsafe(_entityName);
    _builder.append(_nullsafe_1, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u5165\u5E93\u7C7B\u578B:</td>");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdcontent\">");
    RCInStoreType _inStoreType = value.getInStoreType();
    String _entityName_1 = _inStoreType==null?(String)null:_inStoreType.getEntityName();
    String _nullsafe_2 = InStockTemplate.nullsafe(_entityName_1);
    _builder.append(_nullsafe_2, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u4ED3\u7BA1\u5458:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    RCEmployee _operator = value.getOperator();
    String _entityName_2 = _operator==null?(String)null:_operator.getEntityName();
    String _nullsafe_3 = InStockTemplate.nullsafe(_entityName_2);
    _builder.append(_nullsafe_3, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u5907\u6CE8:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"31%\" class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u9001\u8D27\u5355\u53F7:</td>");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdcontent\">");
    String _deliverNumber = value.getDeliverNumber();
    String _nullsafe_4 = InStockTemplate.nullsafe(_deliverNumber);
    _builder.append(_nullsafe_4, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u53D1\u7968\u53F7\u7801:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    String _invoiceNumber = value.getInvoiceNumber();
    String _nullsafe_5 = InStockTemplate.nullsafe(_invoiceNumber);
    _builder.append(_nullsafe_5, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u4F9B\u5E94\u5546:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"31%\" class=\"tdcontent\">");
    RCSupplier _supplier = value.getSupplier();
    String _entityName_3 = _supplier==null?(String)null:_supplier.getEntityName();
    String _nullsafe_6 = InStockTemplate.nullsafe(_entityName_3);
    _builder.append(_nullsafe_6, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<table  class=\"tableLL\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<th width=\"15%\" >\u5165\u5E93\u6279\u53F7</td>");
    _builder.newLine();
    _builder.append("<th width=\"14%\" >\u6761\u7801</td>  ");
    _builder.newLine();
    _builder.append("<th width=\"10%\" >\u7269\u54C1\u7F16\u53F7</td>");
    _builder.newLine();
    _builder.append("<th width=\"10%\" >\u7269\u54C1\u540D\u79F0</td> ");
    _builder.newLine();
    _builder.append("<th width=\"10%\" >\u89C4\u683C\u578B\u53F7</td> ");
    _builder.newLine();
    _builder.append("<th width=\"10%\" >\u54C1\u724C</td> ");
    _builder.newLine();
    _builder.append("<th width=\"8%\" >\u5355\u4EF7\uFF08\u5143\uFF09</td> ");
    _builder.newLine();
    _builder.append("<th width=\"8%\" >\u6570\u91CF</td> ");
    _builder.newLine();
    _builder.append("<th width=\"5%\" >\u5355\u4F4D</td> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("<tbody>");
    _builder.newLine();
    {
      Collection<RCInStockRecordItem> _items = value.getItems();
      final Function1<RCInStockRecordItem,UIInStockRecordItem> _function = new Function1<RCInStockRecordItem,UIInStockRecordItem>() {
          public UIInStockRecordItem apply(final RCInStockRecordItem it) {
            UIInStockRecordItem _transform = itemMapper.transform(it);
            return _transform;
          }
        };
      Iterable<UIInStockRecordItem> _map = IterableExtensions.<RCInStockRecordItem, UIInStockRecordItem>map(_items, _function);
      for(final UIInStockRecordItem record : _map) {
        _builder.append("<tr>");
        _builder.newLine();
        _builder.append("<td>");
        String _sid_1 = record.getSid();
        String _nullsafe_7 = InStockTemplate.nullsafe(_sid_1);
        _builder.append(_nullsafe_7, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td>");
        String _productSid = record.getProductSid();
        String _nullsafe_8 = InStockTemplate.nullsafe(_productSid);
        _builder.append(_nullsafe_8, "");
        _builder.append("</td>");
        _builder.newLineIfNotEmpty();
        _builder.append("<td>");
        String _materialId = record.getMaterialId();
        String _nullsafe_9 = InStockTemplate.nullsafe(_materialId);
        _builder.append(_nullsafe_9, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td>");
        String _productSpecName = record.getProductSpecName();
        String _nullsafe_10 = InStockTemplate.nullsafe(_productSpecName);
        _builder.append(_nullsafe_10, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td>");
        String _typeDesc = record.getTypeDesc();
        String _nullsafe_11 = InStockTemplate.nullsafe(_typeDesc);
        _builder.append(_nullsafe_11, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td>");
        RCMaterialBrandProxy _brand = record.getBrand();
        String _name = _brand.getName();
        _builder.append(_name, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td class=\"tdright\">");
        Double _price = record.getPrice();
        String _nullsafe_12 = InStockTemplate.nullsafe(_price);
        _builder.append(_nullsafe_12, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td class=\"tdright\">");
        Integer _quantity = record.getQuantity();
        String _nullsafe_13 = InStockTemplate.nullsafe(_quantity);
        _builder.append(_nullsafe_13, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("<td>");
        RCProduceSpecificationUnitProxy _unit = record.getUnit();
        String _name_1 = _unit.getName();
        _builder.append(_name_1, "");
        _builder.append("</td> ");
        _builder.newLineIfNotEmpty();
        _builder.append("</tr> ");
        _builder.newLine();
      }
    }
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td>");
    _builder.newLine();
    _builder.append("</tr> <tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td>");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</toby>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"70%\" class=\"tdlabel tdleft tdbottom\">&nbsp;</td>");
    _builder.newLine();
    _builder.append("<td width=\"12%\" class=\"tdlabel tdleft tdbottom\">\u4ED3\u7BA1\u5458:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"18%\" class=\"tdcontent\">&nbsp;</td>  ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</body> ");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    _builder.newLine();
    String _string = _builder.toString();
    return _string;
  }
}
