package com.fudanmed.platform.core.web.server.service.template;

import com.fudanmed.platform.core.common.RCSystemParameter;
import com.fudanmed.platform.core.domain.RCGroupTask;
import com.fudanmed.platform.core.domain.RCMaintenanceTeam;
import com.fudanmed.platform.core.domain.RCOrganization;
import com.fudanmed.platform.core.domain.RCRepairTask;
import com.fudanmed.platform.core.domain.RCSettlement;
import com.fudanmed.platform.core.domain.RCWorkItemTask;
import com.fudanmed.platform.core.warehouse.RCProduceSpecificationUnit;
import com.fudanmed.platform.core.warehouse.RCProductEntry;
import com.fudanmed.platform.core.warehouse.RCProductSpecification;
import com.fudanmed.platform.core.warehouse.RCWorkItemStorage;
import com.uniquesoft.gwt.shared.extensions.Collections3;
import com.uniquesoft.gwt.shared.extensions.Collections3.ItemWithIndex;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class SettlementTemplate {
  public static String settlementTemplate(final RCSettlement settlement, final RCSystemParameter parameter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t\t");
    _builder.append("<html> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<head> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<title>\u7ED3\u7B97\u5355</title> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("<style> ");
    _builder.newLine();
    _builder.append("table");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("border:0px solid black;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("width:22cm;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("border-spacing:0px 7px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("td,th{");
    _builder.newLine();
    _builder.append("color:#000000;");
    _builder.newLine();
    _builder.append("font-size: 12pt; ");
    _builder.newLine();
    _builder.append("font-family:Arial,Microsoft YaHei,SimHei,SimSun;");
    _builder.newLine();
    _builder.append("height:0.5cm;");
    _builder.newLine();
    _builder.append("padding-left:2px;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdlabel ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("border-style:none; ");
    _builder.newLine();
    _builder.append("font-weight:bold;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdleft");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:left;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdright");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:right;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdcenter");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdtop ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("vertical-align:top;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.append(".tdbottom ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdcontent");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border-style:none;");
    _builder.newLine();
    _builder.append("border-bottom:1px solid #000000;");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("thead");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("display:table-header-group;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("width:22cm;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border-collapse:collapse;");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL th");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-top:3px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-bottom:3px;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL td");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("padding:3px 7px 2px 7px;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("font-size: 10pt;");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("</style> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</head> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<body > ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<h2 style=\"width:21cm;text-align:center;font-family:Arial,Microsoft YaHei,SimHei,SimSun;\" >");
    String _orgName = parameter.getOrgName();
    _builder.append(_orgName, "		");
    _builder.append("\u7EF4\u4FEE\u670D\u52A1\u5355\u7ED3\u7B97</h2>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u7ED3\u7B97\u5355\u53F7:</td>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"15%\" class=\"tdcontent\">");
    String _sid = settlement.getSid();
    _builder.append(_sid, "		");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u5F00\u59CB\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date _fromDate = settlement.getFromDate();
    String _format = _simpleDateFormat.format(_fromDate);
    _builder.append(_format, "		");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u7ED3\u675F\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"31%\" class=\"tdcontent\">");
    SimpleDateFormat _simpleDateFormat_1 = new SimpleDateFormat("yyyy-MM-dd");
    Date _toDate = settlement.getToDate();
    String _format_1 = _simpleDateFormat_1.format(_toDate);
    _builder.append(_format_1, "		");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<table  class=\"tableLL\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"10%\" >\u670D\u52A1\u5355\u53F7</td>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"14%\" >\u4F7F\u7528\u90E8\u95E8</td>  ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"10%\" >\u7EF4\u4FEE\u73ED\u7EC4</td>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"10%\" >\u6750\u6599\u540D\u79F0</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"10%\" >\u89C4\u683C</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"5%\" >\u5355\u4F4D</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"8%\" >\u5355\u4EF7\uFF08\u5143\uFF09</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"8%\" >\u6570\u91CF</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th width=\"15%\" >\u7269\u54C1\u6279\u53F7</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    {
      Collection<RCRepairTask> _allItems = settlement.getAllItems();
      for(final RCRepairTask repairReportItem : _allItems) {
        _builder.append("\t\t");
        Collection<RCWorkItemStorage> _storage = repairReportItem.getStorage();
        int storageSize = _storage.size();
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.newLine();
        {
          Collection<RCWorkItemStorage> _storage_1 = repairReportItem.getStorage();
          Iterable<ItemWithIndex<RCWorkItemStorage>> _iteratorWithIndex = Collections3.<RCWorkItemStorage>iteratorWithIndex(_storage_1);
          for(final ItemWithIndex<RCWorkItemStorage> item : _iteratorWithIndex) {
            _builder.append("\t\t");
            _builder.append("<tr>");
            _builder.newLine();
            {
              int _index = item.getIndex();
              boolean _equals = (_index == 0);
              if (_equals) {
                _builder.append("\t\t");
                _builder.append("<td rowspan=");
                _builder.append(storageSize, "		");
                _builder.append(">");
                String _reportSid = repairReportItem.getReportSid();
                _builder.append(_reportSid, "		");
                _builder.append("</td> ");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
                _builder.append("<td rowspan=");
                _builder.append(storageSize, "		");
                _builder.append(" >");
                RCOrganization _reportOrg = repairReportItem.getReportOrg();
                String _entityName = _reportOrg.getEntityName();
                _builder.append(_entityName, "		");
                _builder.append("</td>");
                _builder.newLineIfNotEmpty();
              }
            }
            _builder.append("\t\t");
            _builder.append("<td>");
            RCWorkItemStorage _value = item.getValue();
            RCWorkItemTask _workItem = _value.getWorkItem();
            RCGroupTask _groupTask = _workItem.getGroupTask();
            RCMaintenanceTeam _team = _groupTask.getTeam();
            String _entityName_1 = _team.getEntityName();
            _builder.append(_entityName_1, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<td>");
            RCWorkItemStorage _value_1 = item.getValue();
            RCProductEntry _productEntry = _value_1.getProductEntry();
            String _entityName_2 = _productEntry.getEntityName();
            _builder.append(_entityName_2, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<td>");
            RCWorkItemStorage _value_2 = item.getValue();
            RCProductEntry _productEntry_1 = _value_2.getProductEntry();
            RCProductSpecification _productSpec = _productEntry_1.getProductSpec();
            String _typeDesc = _productSpec.getTypeDesc();
            _builder.append(_typeDesc, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<td>");
            RCWorkItemStorage _value_3 = item.getValue();
            RCProductEntry _productEntry_2 = _value_3.getProductEntry();
            RCProductSpecification _productSpec_1 = _productEntry_2.getProductSpec();
            RCProduceSpecificationUnit _unit = _productSpec_1.getUnit();
            String _entityName_3 = _unit.getEntityName();
            _builder.append(_entityName_3, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<td class=\"tdright\">");
            RCWorkItemStorage _value_4 = item.getValue();
            RCProductEntry _productEntry_3 = _value_4.getProductEntry();
            Double _price = _productEntry_3.getPrice();
            _builder.append(_price, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<td class=\"tdright\">");
            RCWorkItemStorage _value_5 = item.getValue();
            Integer _quantity = _value_5.getQuantity();
            _builder.append(_quantity, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<td>");
            RCWorkItemStorage _value_6 = item.getValue();
            RCProductEntry _productEntry_4 = _value_6.getProductEntry();
            String _sid_1 = _productEntry_4.getSid();
            _builder.append(_sid_1, "		");
            _builder.append("</td> ");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("</tr> ");
            _builder.newLine();
          }
        }
      }
    }
    _builder.append("\t\t");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th colspan= 6>\u603B\u7ED3\u7B97\u91D1\u989D</th> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th colspan= 3>");
    Double _totalAmount = settlement.getTotalAmount();
    _builder.append(_totalAmount, "		");
    _builder.append("\u5143</th> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</toby>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<table>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"40%\" class=\"tdlabel tdleft tdbottom\">&nbsp;</td>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"12%\" class=\"tdlabel tdleft tdbottom\">\u5DE5\u7A0B\u8D1F\u8D23\u4EBA:</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"18%\" class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"12%\" class=\"tdlabel tdleft tdbottom\">\u9662\u65B9\u7B7E\u5B57:</td> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<td width=\"18%\" class=\"tdcontent\">&nbsp;</td>  ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</body> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</html>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.newLine();
    return _builder.toString();
  }
}
