package com.fudanmed.platform.core.web.server.service.template;

import com.fudanmed.platform.core.domain.proxy.RCMaintenanceTeamProxy;
import com.fudanmed.platform.core.domain.proxy.RCOrganizationProxy;
import com.fudanmed.platform.core.web.shared.project.UIRepairTask;
import com.fudanmed.platform.core.web.shared.project.UIRepairTaskStatus;
import com.uniquesoft.gwt.shared.extensions.StringExtensions;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class EBoardTemplate {
  public static String template(final Integer curPage, final Integer totalPage, final String message, final Collection<UIRepairTask> tasks) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("<table width=\"1024px\" align=\"center\" id=\"Table1\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=black>");
    _builder.newLine();
    _builder.append("<tr height=\"73\" >");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<td width=\"974px\" align=\"left\" colspan=2 style=\"color:#ffffff; font-size:200%;\"><IMG  src=\"images/eboard/logo.png\">\u4E0A\u6D77\u590D\u65E6\u533B\u9662\u540E\u52E4\u670D\u52A1\u6709\u9650\u516C\u53F8</td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr height=\"35\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td width=\"974px\"  align=\"center\" background=\"images/eboard/green.jpg\"  valign=\"middle\" colspan=2 style=\"color:#ffffff; font-size:120%;\"><B> \u5F53\u524D\u62A5\u4FEE\u9879\u76EE\u5B9E\u65F6\u72B6\u6001</B></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr height=\"400\">");
    _builder.newLine();
    _builder.append("<td width=\"974px\" id =\"right\" colspan=2 style=\"padding-left:5px;\" valign=\'top\'>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<TABLE  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<TD width=\"100%\" align=\"center\" valign=\"top\"><div  style=\"margin:2px\uFF1Balign:left;width:95%;height:95%;text-align:left\">");
    _builder.newLine();
    _builder.append("\t          \t\t");
    _builder.append("<TABLE width=\"100%\" align=\"center\"  style=\"font-size:15px;\"");
    _builder.newLine();
    _builder.append("\t                        ");
    _builder.append("border=\"0\" >");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<tr style=\"font-size:150%;font-weight:bold;color:red\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"15%\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">\u62A5\u4FEE\u65F6\u95F4</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"19%\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">\u62A5\u4FEE\u79D1\u5BA4</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"8%\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">\u72B6\u6001</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"15%\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">\u7EF4\u4FEE\u73ED\u7EC4</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"11%\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">\u7EF4\u4FEE\u4EBA</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"18%\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">\u62A5\u4FEE\u5185\u5BB9</th>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<th width=\"14%\" style=\"border-bottom:#00ff00 dotted thin;font-size:80%;color:#dddddd\">\u7B2C");
    _builder.append(curPage, "							");
    _builder.append("\u9875\u5171");
    _builder.append(totalPage, "							");
    _builder.append("\u9875</th>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</tr>");
    _builder.newLine();
    {
      for(final UIRepairTask task : tasks) {
        {
          Boolean _isTimeOut = task.getIsTimeOut();
          if ((_isTimeOut).booleanValue()) {
            _builder.append("<TR style=\"color:orange;font-size:125%\">");
            _builder.newLine();
          } else {
            _builder.append("<TR style=\"color:white;font-size:125%\">");
            _builder.newLine();
          }
        }
        _builder.append("                          ");
        _builder.append("<TD height=\"40\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">");
        _builder.newLine();
        _builder.append("                          \t");
        SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        Date _reportTime = task.getReportTime();
        String _format = _simpleDateFormat.format(_reportTime);
        _builder.append(_format, "                          	");
        _builder.newLineIfNotEmpty();
        _builder.append("                          ");
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("                          ");
        _builder.append("<TD height=\"40\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">");
        _builder.newLine();
        _builder.append("                          \t");
        RCOrganizationProxy _reportOrg = task.getReportOrg();
        String _name = _reportOrg==null?(String)null:_reportOrg.getName();
        String _abbreviate = _name==null?(String)null:StringExtensions.abbreviate(_name, 14);
        _builder.append(_abbreviate, "                          	");
        _builder.newLineIfNotEmpty();
        _builder.append("                          ");
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("                          ");
        _builder.append("<TD height=\"40\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">");
        _builder.newLine();
        _builder.append("                          \t");
        UIRepairTaskStatus _status = task.getStatus();
        _builder.append(_status, "                          	");
        _builder.newLineIfNotEmpty();
        _builder.append("                          ");
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("                          ");
        _builder.append("<TD height=\"40\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">");
        _builder.newLine();
        _builder.append("                          \t");
        RCMaintenanceTeamProxy _activeTeam = task.getActiveTeam();
        String _name_1 = _activeTeam==null?(String)null:_activeTeam.getName();
        _builder.append(_name_1, "                          	");
        _builder.newLineIfNotEmpty();
        _builder.append("                          ");
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("                          ");
        _builder.append("<TD height=\"40\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\">");
        _builder.newLine();
        _builder.append("                          \t");
        String _abbtActiveWorkers = task.getAbbtActiveWorkers();
        _builder.append(_abbtActiveWorkers, "                          	");
        _builder.newLineIfNotEmpty();
        _builder.append("                          ");
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("                          ");
        _builder.append("<TD height=\"40\" style=\"border-bottom:#00ff00 dotted thin;text-align:left;\" colspan=2>");
        _builder.newLine();
        _builder.append("                          \t");
        String _comment = task.getComment();
        String _abbreviate_1 = StringExtensions.abbreviate(_comment, 20);
        _builder.append(_abbreviate_1, "                          	");
        _builder.newLineIfNotEmpty();
        _builder.append("                          ");
        _builder.append("</TD>");
        _builder.newLine();
        _builder.append("                        ");
        _builder.append("</TR>");
        _builder.newLine();
      }
    }
    _builder.append("\t\t\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t            \t");
    _builder.append("</TABLE>");
    _builder.newLine();
    _builder.append("\t                      ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</TD>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</TABLE>");
    _builder.newLine();
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr height=\"242\">");
    _builder.newLine();
    _builder.append("<td width=\"300px\" id =\"left\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<TABLE  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("<TD width=\"100%\" height=\"32\" align=\"center\" >");
    _builder.newLine();
    _builder.append("           \t\t");
    _builder.append("<div  style=\"padding-top: 5px;width:280px;background-image:url(images/eboard/bj_green.jpg);\" ><b style=\"font-size:120%\">\u91CD\u8981\u901A\u77E5</b></div>");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("</TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<TD width=\"100%\" height=\"312\" align=\"center\" id=\"TD1\"  valign=\"top\" >");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<marquee direction=\'up\' scrollamount=\'1\' scrolldelay=\'10\' width=\'280\' height=\'130\' style=\"padding:3px;color:orange\">");
    _builder.newLine();
    _builder.append("          ");
    _builder.append(message, "          ");
    _builder.newLineIfNotEmpty();
    _builder.append("          ");
    _builder.append("</marquee>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</TD>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</TABLE>                ");
    _builder.newLine();
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("<td width=\"760px\" id =\"right\" style=\"padding-left:5px;\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<TABLE  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<TR>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<TD width=\"100%\" height=\"139\" align=\"center\" ><IMG height=\"108\" src=\"images/eboard/left.jpg\"><IMG src=\"images/eboard/ban.jpg\"></TD>                ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("</TR>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</TABLE>");
    _builder.newLine();
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>\t\t");
    _builder.newLine();
    String _string = _builder.toString();
    return _string;
  }
}
