package com.fudanmed.platform.core.web.server.service.template;

import com.fudanmed.platform.core.common.RCFaultReportSource;
import com.fudanmed.platform.core.common.RCSystemParameter;
import com.fudanmed.platform.core.domain.RCEmployee;
import com.fudanmed.platform.core.domain.RCFaultType;
import com.fudanmed.platform.core.domain.RCGroupTask;
import com.fudanmed.platform.core.domain.RCMaintenanceTeam;
import com.fudanmed.platform.core.domain.RCOrganization;
import com.fudanmed.platform.core.domain.RCRepairTask;
import com.fudanmed.platform.core.domain.RCWorkItemTask;
import com.fudanmed.platform.core.warehouse.RCProduceSpecificationUnit;
import com.fudanmed.platform.core.warehouse.RCProductEntry;
import com.fudanmed.platform.core.warehouse.RCProductSpecification;
import com.fudanmed.platform.core.warehouse.RCRecordItem;
import com.fudanmed.platform.core.warehouse.RCWorkItemOutStockRecord;
import com.fudanmed.platform.core.warehouse.RCWorkItemStockRecordItem;
import com.google.common.base.Objects;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Template {
  public static String nullsafe(final String s) {
    String _xifexpression = null;
    boolean _equals = Objects.equal(s, null);
    if (_equals) {
      _xifexpression = "&nbsp;";
    } else {
      _xifexpression = s;
    }
    return _xifexpression;
  }
  
  public static String workItem(final RCWorkItemTask workItemTask, final RCSystemParameter parameter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<html> ");
    _builder.newLine();
    _builder.append("<head> ");
    _builder.newLine();
    _builder.append("<title>worksheet</title> ");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"> ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("<style> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("table");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("border:0px solid black;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("width:22cm;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("border-spacing:0px 7px;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("td,th{");
    _builder.newLine();
    _builder.append("color:#000000;");
    _builder.newLine();
    _builder.append("font-size: 12pt; ");
    _builder.newLine();
    _builder.append("font-family:Arial,Microsoft YaHei,SimHei,SimSun;");
    _builder.newLine();
    _builder.append("height:0.5cm;");
    _builder.newLine();
    _builder.append("padding-left:2px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdlabel ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("border-style:none; ");
    _builder.newLine();
    _builder.append("font-weight:bold;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdleft");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:left;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdright");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:right;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdcenter");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tdtop ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("vertical-align:top;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.append(".tdbottom ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdcontent");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border-style:none;");
    _builder.newLine();
    _builder.append("border-bottom:1px solid #000000;");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tddiv");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border:2px solid #000000;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".divLL/*\u7EDD\u5BF9\u5B9A\u4F4D*/");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("position:absolute;");
    _builder.newLine();
    _builder.append("left:7.3cm;");
    _builder.newLine();
    _builder.append("top:5.6cm;");
    _builder.newLine();
    _builder.append("width:15cm;");
    _builder.newLine();
    _builder.append("height:4cm;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tableLL");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("width:100%;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border:2px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border-collapse:collapse;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL th");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("border:2px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-top:3px;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("padding-bottom:3px;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tableLL td");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("border:2px solid #000000;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("padding:3px 7px 2px 7px;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("font-size: 10pt;");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("</style> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</head> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<body > ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<h2 style=\"width:21cm;text-align:center;font-family:Arial,Microsoft YaHei,SimHei,SimSun;\">");
    String _orgName = parameter.getOrgName();
    _builder.append(_orgName, "");
    _builder.append("\u7EF4\u4FEE\u670D\u52A1\u5355</h2>");
    _builder.newLineIfNotEmpty();
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u62A5\u4FEE\u5355\u53F7:</td><!--\u5C31\u662F\u5DE5\u5355\u53F7\u4EE5\u4E0B\u662F\u62A5\u4FEE\u5355-->");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdcontent\">");
    RCGroupTask _groupTask = workItemTask.getGroupTask();
    RCRepairTask _repairTask = _groupTask.getRepairTask();
    String _reportSid = _repairTask.getReportSid();
    _builder.append(_reportSid, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u62A5\u4FEE\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    RCGroupTask _groupTask_1 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_1 = _groupTask_1.getRepairTask();
    Date _reportTime = _repairTask_1.getReportTime();
    String _format = _simpleDateFormat.format(_reportTime);
    _builder.append(_format, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdbottom\">\u62A5\u4FEE\u79D1\u5BA4:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"31%\" class=\"tdcontent\">");
    RCGroupTask _groupTask_2 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_2 = _groupTask_2.getRepairTask();
    RCOrganization _reportOrg = _repairTask_2.getReportOrg();
    String _entityName = _reportOrg==null?(String)null:_reportOrg.getEntityName();
    String _nullsafe = Template.nullsafe(_entityName);
    _builder.append(_nullsafe, "");
    _builder.append("</td> <!--\u79D1\u5BA4+\u62A5\u4FEE\u5730\u70B9-->");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabel tdleft tdbottom\">\u8C03\u5EA6\u4EBA\u5458:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">");
    RCGroupTask _groupTask_3 = workItemTask.getGroupTask();
    RCEmployee _operator = _groupTask_3.getOperator();
    String _entityName_1 = _operator.getEntityName();
    _builder.append(_entityName_1, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td class=\"tdlabel tdleft tdbottom\">\u7EF4\u4FEE\u73ED\u7EC4:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">");
    RCGroupTask _groupTask_4 = workItemTask.getGroupTask();
    RCMaintenanceTeam _team = _groupTask_4.getTeam();
    String _entityName_2 = _team==null?(String)null:_team.getEntityName();
    String _nullsafe_1 = Template.nullsafe(_entityName_2);
    _builder.append(_nullsafe_1, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td class=\"tdlabel tdleft tdbottom\">\u7EF4\u4FEE\u4EBA\u5458:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">");
    {
      Collection<RCEmployee> _workers = workItemTask.getWorkers();
      boolean _hasElements = false;
      for(final RCEmployee p : _workers) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(",", "");
        }
        String _entityName_3 = p.getEntityName();
        _builder.append(_entityName_3, "");
      }
    }
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td  class=\"tdlabel tdleft tdbottom\">\u62A5\u4FEE\u6765\u6E90:</td> ");
    _builder.newLine();
    _builder.append("<td  class=\"tdcontent\">");
    RCGroupTask _groupTask_5 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_3 = _groupTask_5.getRepairTask();
    RCFaultReportSource _faultReportSource = _repairTask_3.getFaultReportSource();
    String _entityName_4 = _faultReportSource==null?(String)null:_faultReportSource.getEntityName();
    String _nullsafe_2 = Template.nullsafe(_entityName_4);
    _builder.append(_nullsafe_2, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td  class=\"tdlabel tdleft tdbottom\">\u62A5\u4FEE\u4EBA:</td> ");
    _builder.newLine();
    _builder.append("<td  class=\"tdcontent\">");
    RCGroupTask _groupTask_6 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_4 = _groupTask_6.getRepairTask();
    String _reporterName = _repairTask_4.getReporterName();
    String _nullsafe_3 = Template.nullsafe(_reporterName);
    String _plus = (_nullsafe_3 + "&nbsp;");
    RCGroupTask _groupTask_7 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_5 = _groupTask_7.getRepairTask();
    String _reporterPhone = _repairTask_5.getReporterPhone();
    String _nullsafe_4 = Template.nullsafe(_reporterPhone);
    String _plus_1 = (_plus + _nullsafe_4);
    _builder.append(_plus_1, "");
    _builder.append("</td> <!--\u79D1\u5BA4+\u62A5\u4FEE\u5730\u70B9-->");
    _builder.newLineIfNotEmpty();
    _builder.append("<td  class=\"tdlabel tdleft tdbottom\">\u62A5\u4FEE\u5730\u70B9:</td> ");
    _builder.newLine();
    _builder.append("<td  class=\"tdcontent\">");
    RCGroupTask _groupTask_8 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_6 = _groupTask_8.getRepairTask();
    String _location = _repairTask_6.getLocation();
    String _nullsafe_5 = Template.nullsafe(_location);
    _builder.append(_nullsafe_5, "");
    _builder.append("</td> <!--\u79D1\u5BA4+\u62A5\u4FEE\u5730\u70B9-->");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdleft tdtop\" rowspan=3>\u62A5\u4FEE\u7C7B\u522B:</td>");
    _builder.newLine();
    _builder.append("<td width=\"19%\" class=\"tddiv tdleft tdtop\"rowspan=3>");
    _builder.newLine();
    _builder.append("\t");
    RCGroupTask _groupTask_9 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_7 = _groupTask_9.getRepairTask();
    RCFaultType _faultType = _repairTask_7.getFaultType();
    String _entityName_5 = _faultType==null?(String)null:_faultType.getEntityName();
    String _nullsafe_6 = Template.nullsafe(_entityName_5);
    _builder.append(_nullsafe_6, "	");
    String _xifexpression = null;
    RCGroupTask _groupTask_10 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_8 = _groupTask_10.getRepairTask();
    RCFaultType _faultType_1 = _repairTask_8.getFaultType();
    Boolean _needAudit = _faultType_1.getNeedAudit();
    if ((_needAudit).booleanValue()) {
      _xifexpression = "(\u9700\u5BA1\u6279)";
    } else {
      _xifexpression = "";
    }
    _builder.append(_xifexpression, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabel tdcenter tdtop\"width=\"38%\">\u6750\u6599\u4F7F\u7528</td> ");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdlabel tdright tdtop\">\u4ED3\u7BA1\u5458\uFF1A</td> ");
    _builder.newLine();
    _builder.append("<td width=\"22%\" class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> <td colspan=3>&nbsp;</td> </tr> ");
    _builder.newLine();
    _builder.append("<tr> <td colspan=3>&nbsp;</td> </tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td  class=\"tdlabel tdleft tdtop\" rowspan=5>\u62A5\u4FEE\u5185\u5BB9:</td>");
    _builder.newLine();
    _builder.append("<td  class=\"tddiv tdleft tdtop\"rowspan=5>");
    RCGroupTask _groupTask_11 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_9 = _groupTask_11.getRepairTask();
    String _comment = _repairTask_9.getComment();
    String _nullsafe_7 = Template.nullsafe(_comment);
    _builder.append(_nullsafe_7, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td>&nbsp;</td>\t\t\t");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr > <td colspan=3>&nbsp;</td> </tr> ");
    _builder.newLine();
    _builder.append("<tr> <td colspan=3>&nbsp;</td> </tr> ");
    _builder.newLine();
    _builder.append("<tr> <td colspan=3>&nbsp;</td> </tr> ");
    _builder.newLine();
    _builder.append("<tr> <td colspan=3>&nbsp;</td> </tr> ");
    _builder.newLine();
    _builder.append("<table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"11%\" class=\"tdlabel tdright tdbottom\">\u5DE5\u5355\u7F16\u53F7\uFF1A</td> ");
    _builder.newLine();
    _builder.append("<td width=\"19%\" class=\"tdcontent\">");
    String _sid = workItemTask.getSid();
    String _nullsafe_8 = Template.nullsafe(_sid);
    _builder.append(_nullsafe_8, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"15%\" class=\"tdlabel tdleft tdbottom\">\u5230\u8FBE\u65F6\u95F4:</td>");
    _builder.newLine();
    _builder.append("<td width=\"19%\" class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdlabel tdleft tdbottom\">\u5B8C\u6210\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"22%\" class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabel tdleft tdtop\" rowspan=5>\u9662\u65B9\u610F\u89C1\uFF1A</td>");
    _builder.newLine();
    _builder.append("<td class=\"tddiv tdright tdbottom\" rowspan=5>\u7B7E\u5B57\uFF1A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabel tdtop\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabel tdright tdbottom\" >\u7EF4\u4FEE\u5185\u5BB9:&nbsp;&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tddiv tdleft tdtop\" rowspan=5 colspan=2>&nbsp;</td>");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td  width class=\"tdlabel tdleft tdbottom\">\u5DE5\u7A0B\u90E8\u8D1F\u8D23\u4EBA:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">&nbsp;</td>");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("</table> ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("<div class=\"divLL\">");
    _builder.newLine();
    _builder.append("<table  class=\"tableLL\">");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<th width=\"23%\" >\u6750\u6599\u540D\u79F0</td> ");
    _builder.newLine();
    _builder.append("<th width=\"28%\" >\u89C4\u683C</td> ");
    _builder.newLine();
    _builder.append("<th width=\"9%\" >\u6570\u91CF</td> ");
    _builder.newLine();
    _builder.append("<th width=\"8%\" >\u5355\u4F4D</td> ");
    _builder.newLine();
    _builder.append("<th width=\"15%\" >\u5355\u4EF7(\u5143)</td> ");
    _builder.newLine();
    _builder.append("<th width=\"17%\" >\u91D1\u989D(\u5143)</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("<td>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("<th colspan= 5>\u8D39\u7528\u5408\u8BA1</th> ");
    _builder.newLine();
    _builder.append("<th>&nbsp;</th> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</body> ");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    return _builder.toString();
  }
  
  public static String workItem1(final RCWorkItemTask workItemTask, final RCSystemParameter parameter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<html> ");
    _builder.newLine();
    _builder.append("<head> ");
    _builder.newLine();
    _builder.append("<title>worksheet</title> ");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<style> ");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("td{");
    _builder.newLine();
    _builder.append("/*font-family: \"\u5B8B\u4F53\";*/ ");
    _builder.newLine();
    _builder.append("font-size: 10pt; ");
    _builder.newLine();
    _builder.append("padding-bottom:10px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdlabeltop ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("border-style:none; ");
    _builder.newLine();
    _builder.append("text-align:left;");
    _builder.newLine();
    _builder.append("vertical-align:top;");
    _builder.newLine();
    _builder.append("padding:5px;");
    _builder.newLine();
    _builder.append("font-weight:bold;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.append(".tdlabelbottom ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("border-style:none; ");
    _builder.newLine();
    _builder.append("text-align:left;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("padding:5px;");
    _builder.newLine();
    _builder.append("font-weight:bold;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.append(".tdcontent");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border-style:none;");
    _builder.newLine();
    _builder.append("border-bottom:1px solid #000000;");
    _builder.newLine();
    _builder.append("text-align:center;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("padding:5px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append(".tddivtop");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append("text-align:left;");
    _builder.newLine();
    _builder.append("vertical-align:top;");
    _builder.newLine();
    _builder.append("padding:5px;");
    _builder.newLine();
    _builder.append("margin:5px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tdlabelbottomright ");
    _builder.newLine();
    _builder.append("{ ");
    _builder.newLine();
    _builder.append("border-style:none; ");
    _builder.newLine();
    _builder.append("text-align:right;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("padding:5px;");
    _builder.newLine();
    _builder.append("font-weight:bold;");
    _builder.newLine();
    _builder.append("} ");
    _builder.newLine();
    _builder.newLine();
    _builder.append(".tddivbottom");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("border:1px solid #000000;");
    _builder.newLine();
    _builder.append("text-align:right;");
    _builder.newLine();
    _builder.append("vertical-align:bottom;");
    _builder.newLine();
    _builder.append("padding:5px;");
    _builder.newLine();
    _builder.append("margin:5px;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</style> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</head> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<body > ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<center><h2>");
    String _orgName = parameter.getOrgName();
    _builder.append(_orgName, "");
    _builder.append("\u7EF4\u4FEE\u670D\u52A1\u5355</h2></center>");
    _builder.newLineIfNotEmpty();
    _builder.append("<table width=\"100%\" border=\"0\" align=\"center\" > ");
    _builder.newLine();
    _builder.append("<!--\u4EE5\u4E0B\u662F\u62A5\u4FEE\u5355-->");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u5355\u53F7:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"15%\" class=\"tdcontent\">");
    RCGroupTask _groupTask = workItemTask.getGroupTask();
    RCRepairTask _repairTask = _groupTask.getRepairTask();
    String _reportSid = _repairTask.getReportSid();
    _builder.append(_reportSid, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    RCGroupTask _groupTask_1 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_1 = _groupTask_1.getRepairTask();
    Date _reportTime = _repairTask_1.getReportTime();
    String _format = _simpleDateFormat.format(_reportTime);
    _builder.append(_format, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u79D1\u5BA4:</td> ");
    _builder.newLine();
    _builder.append("<td width=\"20%\" class=\"tdcontent\">");
    RCGroupTask _groupTask_2 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_2 = _groupTask_2.getRepairTask();
    RCOrganization _reportOrg = _repairTask_2.getReportOrg();
    String _entityName = _reportOrg==null?(String)null:_reportOrg.getEntityName();
    String _nullsafe = Template.nullsafe(_entityName);
    _builder.append(_nullsafe, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabelbottom\">\u8C03\u5EA6\u4EBA\u5458:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">");
    RCGroupTask _groupTask_3 = workItemTask.getGroupTask();
    RCEmployee _operator = _groupTask_3.getOperator();
    String _entityName_1 = _operator.getEntityName();
    _builder.append(_entityName_1, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td class=\"tdlabelbottom\">\u62A5\u4FEE\u4EBA:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">");
    RCGroupTask _groupTask_4 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_3 = _groupTask_4.getRepairTask();
    RCEmployee _reporter = _repairTask_3.getReporter();
    String _entityName_2 = _reporter==null?(String)null:_reporter.getEntityName();
    String _nullsafe_1 = Template.nullsafe(_entityName_2);
    _builder.append(_nullsafe_1, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("<td class=\"tdlabelbottom\">\u8054\u7CFB\u7535\u8BDD:</td> ");
    _builder.newLine();
    _builder.append("<td class=\"tdcontent\">");
    RCGroupTask _groupTask_5 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_4 = _groupTask_5.getRepairTask();
    RCEmployee _reporter_1 = _repairTask_4.getReporter();
    String _phone = _reporter_1==null?(String)null:_reporter_1.getPhone();
    String _nullsafe_2 = Template.nullsafe(_phone);
    _builder.append(_nullsafe_2, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("<td class=\"tdlabelbottom\">\u62A5\u4FEE\u5730\u70B9:</td> ");
    _builder.newLine();
    _builder.append("<td colspan=5 class=\"tdcontent\">");
    RCGroupTask _groupTask_6 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_5 = _groupTask_6.getRepairTask();
    String _location = _repairTask_5.getLocation();
    String _nullsafe_3 = Template.nullsafe(_location);
    _builder.append(_nullsafe_3, "");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td  colspan=6 width=\"100%\"> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" >");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<tr height=\"150px\"> ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<td width=\"15%\" class=\"tdlabeltop\">\u62A5\u4FEE\u7C7B\u522B:</td> ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<td width=\"30%\" class=\"tddivtop\">");
    RCGroupTask _groupTask_7 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_6 = _groupTask_7.getRepairTask();
    RCFaultType _faultType = _repairTask_6.getFaultType();
    String _entityName_3 = _faultType==null?(String)null:_faultType.getEntityName();
    String _nullsafe_4 = Template.nullsafe(_entityName_3);
    _builder.append(_nullsafe_4, "			");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("<td width=\"15%\" class=\"tdlabeltop\" >\u62A5\u4FEE\u5185\u5BB9:</td> ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<td width=\"40%\" class=\"tddivtop\" >");
    RCGroupTask _groupTask_8 = workItemTask.getGroupTask();
    RCRepairTask _repairTask_7 = _groupTask_8.getRepairTask();
    String _comment = _repairTask_7.getComment();
    String _nullsafe_5 = Template.nullsafe(_comment);
    _builder.append(_nullsafe_5, "			");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\">\u5DE5\u5355\u53F7:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdcontent\">");
    String _sid = workItemTask.getSid();
    String _nullsafe_6 = Template.nullsafe(_sid);
    _builder.append(_nullsafe_6, "	");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\">\u7EF4\u4FEE\u73ED\u7EC4:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdcontent\">");
    RCGroupTask _groupTask_9 = workItemTask.getGroupTask();
    RCMaintenanceTeam _team = _groupTask_9.getTeam();
    String _entityName_4 = _team==null?(String)null:_team.getEntityName();
    String _nullsafe_7 = Template.nullsafe(_entityName_4);
    _builder.append(_nullsafe_7, "	");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\">\u5230\u8FBE\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\">\u7EF4\u4FEE\u4EBA\u5458:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td colspan=\"3\" class=\"tdcontent\">");
    {
      Collection<RCEmployee> _workers = workItemTask.getWorkers();
      boolean _hasElements = false;
      for(final RCEmployee p : _workers) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(",", "	");
        }
        String _entityName_5 = p.getEntityName();
        _builder.append(_entityName_5, "	");
      }
    }
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\">\u5B8C\u6210\u65F6\u95F4:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdcontent\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabeltop\">\u7EF4\u4FEE\u8BF4\u660E:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tddivtop\" colspan=5 height=\"120px\">&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabeltop\">\u9662\u65B9\u610F\u89C1:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tddivbottom\" colspan=5 height=\"120px\">\u7B7E\u5B57\uFF1A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr> ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\" colspan=6>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("</tr>  ");
    _builder.newLine();
    _builder.append("<tr> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottom\" colspan=3>&nbsp;</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdlabelbottomright\"colspan=2 >\u5DE5\u7A0B\u90E8\u8D1F\u8D23\u4EBA:</td> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<td class=\"tdcontent\">&nbsp;</td>");
    _builder.newLine();
    _builder.append("</tr>  ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</body> ");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    _builder.newLine();
    String _string = _builder.toString();
    return _string;
  }
  
  public static String workItemOutStockFit(final RCWorkItemOutStockRecord record) {
    String _xblockexpression = null;
    {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t\t");
      _builder.append("<html> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<head> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<title> </title> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<style> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("table");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("border:0px solid black;");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("width:22cm;");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("border-spacing:0px 7px;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("td,th{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("font-size: 12pt; ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("font-family:Arial,Microsoft YaHei,SimHei,SimSun;;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("height:0.5cm;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("padding-left:2px;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdlabel ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{ ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("border-style:none; ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("font-weight:bold;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdleft");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("text-align:left;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("} ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdright");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("text-align:right;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("} ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdcenter");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("text-align:center;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdtop ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{ ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("vertical-align:top;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("} ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdbottom ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{ ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("vertical-align:bottom;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("} ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tdcontent");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("border-style:none;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("border-bottom:1px solid #000000;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("text-align:center;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("vertical-align:bottom;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tddiv");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("border:1px solid #aaaaaa;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".divLL/*\u7EDD\u5BF9\u5B9A\u4F4D*/");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("position:absolute;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("left:7.3cm;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("top:6.4cm;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("width:15cm;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("height:4cm;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tableLL");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("width:100%;");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("border:0px solid #000000;");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("border-collapse:collapse;");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tableLL th");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("border:0px solid #000000;");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("font-weight:bold;");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("padding-top:3px;");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("padding-bottom:3px;");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append(".tableLL td");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("border:0px solid #000000;");
      _builder.newLine();
      _builder.append("\t\t  ");
      _builder.append("padding:3px 7px 2px 7px;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</style> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("</head> ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<body > ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<div class=\"divLL\">");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("<table  class=\"tableLL\">");
      _builder.newLine();
      _builder.newLine();
      {
        Collection<RCWorkItemStockRecordItem> _items = record.getItems();
        for(final RCWorkItemStockRecordItem item : _items) {
          _builder.append("\t\t");
          _builder.append("<tr>");
          _builder.newLine();
          _builder.append("\t\t");
          _builder.append("<td width=\"23%\" class=\"tdleft\">");
          RCRecordItem _recordItem = item.getRecordItem();
          RCProductEntry _productEntry = _recordItem.getProductEntry();
          RCProductSpecification _productSpec = _productEntry.getProductSpec();
          String _entityName = _productSpec.getEntityName();
          String _nullsafe = Template.nullsafe(_entityName);
          _builder.append(_nullsafe, "		");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          _builder.append("<td width=\"28%\"class=\"tdcenter\">");
          RCRecordItem _recordItem_1 = item.getRecordItem();
          RCProductEntry _productEntry_1 = _recordItem_1.getProductEntry();
          RCProductSpecification _productSpec_1 = _productEntry_1.getProductSpec();
          String _typeDesc = _productSpec_1.getTypeDesc();
          String _nullsafe_1 = Template.nullsafe(_typeDesc);
          _builder.append(_nullsafe_1, "		");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          _builder.append("<td width=\"9%\"class=\"tdright\">");
          RCRecordItem _recordItem_2 = item.getRecordItem();
          Integer _quantity = _recordItem_2.getQuantity();
          String _string = _quantity.toString();
          String _nullsafe_2 = Template.nullsafe(_string);
          _builder.append(_nullsafe_2, "		");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          _builder.append("<td width=\"8%\"class=\"tdcenter\">");
          RCRecordItem _recordItem_3 = item.getRecordItem();
          RCProductEntry _productEntry_2 = _recordItem_3.getProductEntry();
          RCProductSpecification _productSpec_2 = _productEntry_2.getProductSpec();
          RCProduceSpecificationUnit _unit = _productSpec_2.getUnit();
          String _entityName_1 = _unit==null?(String)null:_unit.getEntityName();
          String _nullsafe_3 = Template.nullsafe(_entityName_1);
          _builder.append(_nullsafe_3, "		");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          _builder.append("<td width=\"15%\"class=\"tdright\">");
          RCRecordItem _recordItem_4 = item.getRecordItem();
          RCProductEntry _productEntry_3 = _recordItem_4.getProductEntry();
          Double _price = _productEntry_3.getPrice();
          String _string_1 = _price.toString();
          String _nullsafe_4 = Template.nullsafe(_string_1);
          _builder.append(_nullsafe_4, "		");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          _builder.append("<td width=\"17%\"class=\"tdright\">");
          RCRecordItem _recordItem_5 = item.getRecordItem();
          Double _totalAmount = _recordItem_5.getTotalAmount();
          String _string_2 = _totalAmount.toString();
          String _nullsafe_5 = Template.nullsafe(_string_2);
          _builder.append(_nullsafe_5, "		");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t");
          _builder.append("</tr> ");
          _builder.newLine();
        }
      }
      final CharSequence p1 = _builder;
      String p2 = "";
      Collection<RCWorkItemStockRecordItem> _items_1 = record.getItems();
      int i = _items_1.size();
      boolean _lessThan = (i < 5);
      boolean _while = _lessThan;
      while (_while) {
        {
          String _plus = (p2 + 
            "\n\t\t\t<tr>\n\t\t\t<td width=\"23%\" class=\"tdleft\">&nbsp;</td> \n\t\t\t<td width=\"28%\"class=\"tdcenter\">&nbsp;</td> \n\t\t\t<td width=\"9%\"class=\"tdright\">&nbsp;</td> \n\t\t\t<td width=\"8%\"class=\"tdcenter\">&nbsp;</td> \n\t\t\t<td width=\"15%\"class=\"tdright\">&nbsp;</td> \n\t\t\t<td width=\"17%\"class=\"tdright\">&nbsp;</td> \n\t\t\t</tr> \n\t\t\t");
          p2 = _plus;
          int _plus_1 = (i + 1);
          i = _plus_1;
        }
        boolean _lessThan_1 = (i < 5);
        _while = _lessThan_1;
      }
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("<tr>");
      _builder_1.newLine();
      _builder_1.append("<th colspan=5>&nbsp;</th> ");
      _builder_1.newLine();
      _builder_1.append("<td class=\"tdright\">");
      Double _totalAmount_1 = record.getTotalAmount();
      String _string_3 = _totalAmount_1.toString();
      String _nullsafe_6 = Template.nullsafe(_string_3);
      _builder_1.append(_nullsafe_6, "");
      _builder_1.append("</td> ");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append(" ");
      _builder_1.newLine();
      _builder_1.append("</tr> ");
      _builder_1.newLine();
      _builder_1.append("</table>");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("</div>");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("</body> ");
      _builder_1.newLine();
      _builder_1.append("</html>");
      _builder_1.newLine();
      final CharSequence p3 = _builder_1;
      String _string_4 = p1.toString();
      String _string_5 = p2.toString();
      String _plus = (_string_4 + _string_5);
      String _string_6 = p3.toString();
      String _plus_1 = (_plus + _string_6);
      _xblockexpression = (_plus_1);
    }
    return _xblockexpression;
  }
  
  public static String workItemOutStock(final RCWorkItemOutStockRecord record, final RCSystemParameter parameter) {
    String _xblockexpression = null;
    {
      final RCWorkItemTask workItemTask = record.getWorkItem();
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("\t\t\t");
      _builder.append("<html> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<head> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<title>\u9886\u6599\u5355</title> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"> ");
      _builder.newLine();
      _builder.append("\t\t\t ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("<style> ");
      _builder.newLine();
      _builder.newLine();
      _builder.append("table");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("{");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("border:0px solid black;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("width:22cm;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("    ");
      _builder.append("border-spacing:0px 7px;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("  ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("td,th{");
      _builder.newLine();
      _builder.append("color:#000000;");
      _builder.newLine();
      _builder.append("font-size: 12pt; ");
      _builder.newLine();
      _builder.append("font-family:Arial,Microsoft YaHei,SimHei,SimSun;");
      _builder.newLine();
      _builder.append("height:0.5cm;");
      _builder.newLine();
      _builder.append("padding-left:2px;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tdlabel ");
      _builder.newLine();
      _builder.append("{ ");
      _builder.newLine();
      _builder.append("border-style:none; ");
      _builder.newLine();
      _builder.append("font-weight:bold;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.append(".tdleft");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("text-align:left;");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tdright");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("text-align:right;");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tdcenter");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("text-align:center;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.append(".tdtop ");
      _builder.newLine();
      _builder.append("{ ");
      _builder.newLine();
      _builder.append("vertical-align:top;");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.append(".tdbottom ");
      _builder.newLine();
      _builder.append("{ ");
      _builder.newLine();
      _builder.append("vertical-align:bottom;");
      _builder.newLine();
      _builder.append("} ");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tdcontent");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("border-style:none;");
      _builder.newLine();
      _builder.append("border-bottom:1px solid #000000;");
      _builder.newLine();
      _builder.append("text-align:center;");
      _builder.newLine();
      _builder.append("vertical-align:bottom;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("thead");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("   ");
      _builder.append("display:table-header-group;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tableLL");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("width:22cm;");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("border:1px solid #000000;");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("border-collapse:collapse;");
      _builder.newLine();
      _builder.newLine();
      _builder.append(" ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tableLL th");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("border:1px solid #000000;");
      _builder.newLine();
      _builder.append(" ");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("padding-top:3px;");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("padding-bottom:3px;");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append(".tableLL td");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("border:1px solid #000000;");
      _builder.newLine();
      _builder.append(" ");
      _builder.append("padding:3px 7px 2px 7px;");
      _builder.newLine();
      _builder.append("font-size: 10pt;");
      _builder.newLine();
      _builder.newLine();
      _builder.append(" ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("</style> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</head> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<body > ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<center><h2 style=\"width:21cm;text-align:center;font-family:Arial,Microsoft YaHei,SimHei,SimSun;\" >");
      String _orgName = parameter.getOrgName();
      _builder.append(_orgName, "			");
      _builder.append("\u7EF4\u4FEE\u670D\u52A1\u5355-\u9886\u6599\u5355</h2></center>");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<table width=\"100%\" border=\"0\" align=\"center\" > ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<!--\u4EE5\u4E0B\u662F\u62A5\u4FEE\u5355-->");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u5355\u53F7:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\" class=\"tdcontent\">");
      RCGroupTask _groupTask = workItemTask.getGroupTask();
      RCRepairTask _repairTask = _groupTask.getRepairTask();
      String _reportSid = _repairTask.getReportSid();
      _builder.append(_reportSid, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u65F6\u95F4:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"20%\" class=\"tdcontent\">");
      SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
      RCGroupTask _groupTask_1 = workItemTask.getGroupTask();
      RCRepairTask _repairTask_1 = _groupTask_1.getRepairTask();
      Date _reportTime = _repairTask_1.getReportTime();
      String _format = _simpleDateFormat.format(_reportTime);
      _builder.append(_format, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u79D1\u5BA4:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"20%\" class=\"tdcontent\">");
      RCGroupTask _groupTask_2 = workItemTask.getGroupTask();
      RCRepairTask _repairTask_2 = _groupTask_2.getRepairTask();
      RCOrganization _reportOrg = _repairTask_2.getReportOrg();
      String _entityName = _reportOrg==null?(String)null:_reportOrg.getEntityName();
      String _nullsafe = Template.nullsafe(_entityName);
      _builder.append(_nullsafe, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("</tr> ");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u5730\u70B9:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"85%\" colspan=3 class=\"tdcontent\">");
      RCGroupTask _groupTask_3 = workItemTask.getGroupTask();
      RCRepairTask _repairTask_3 = _groupTask_3.getRepairTask();
      String _location = _repairTask_3.getLocation();
      String _nullsafe_1 = Template.nullsafe(_location);
      _builder.append(_nullsafe_1, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\" class=\"tdlabelbottom\">\u62A5\u4FEE\u4EBA:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"20%\" class=\"tdcontent\">");
      RCGroupTask _groupTask_4 = workItemTask.getGroupTask();
      RCRepairTask _repairTask_4 = _groupTask_4.getRepairTask();
      String _reporterName = _repairTask_4.getReporterName();
      String _nullsafe_2 = Template.nullsafe(_reporterName);
      String _plus = (_nullsafe_2 + "&nbsp;");
      RCGroupTask _groupTask_5 = workItemTask.getGroupTask();
      RCRepairTask _repairTask_5 = _groupTask_5.getRepairTask();
      String _reporterPhone = _repairTask_5.getReporterPhone();
      String _nullsafe_3 = Template.nullsafe(_reporterPhone);
      String _plus_1 = (_plus + _nullsafe_3);
      _builder.append(_plus_1, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("</tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<!--\u4EE5\u4E0B\u662F\u5DE5\u5355-->");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdlabelbottom\">\u5DE5\u5355\u53F7:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdcontent\">");
      String _sid = workItemTask.getSid();
      String _nullsafe_4 = Template.nullsafe(_sid);
      _builder.append(_nullsafe_4, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdlabelbottom\">\u7EF4\u4FEE\u73ED\u7EC4:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdcontent\">");
      RCGroupTask _groupTask_6 = workItemTask.getGroupTask();
      RCMaintenanceTeam _team = _groupTask_6.getTeam();
      String _entityName_1 = _team==null?(String)null:_team.getEntityName();
      String _nullsafe_5 = Template.nullsafe(_entityName_1);
      _builder.append(_nullsafe_5, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdlabelbottom\">\u7EF4\u4FEE\u4EBA\u5458:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdcontent\">");
      {
        Collection<RCEmployee> _workers = workItemTask.getWorkers();
        boolean _hasElements = false;
        for(final RCEmployee p : _workers) {
          if (!_hasElements) {
            _hasElements = true;
          } else {
            _builder.appendImmediate(",", "			");
          }
          String _entityName_2 = p.getEntityName();
          _builder.append(_entityName_2, "			");
        }
      }
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("</tr> ");
      _builder.newLine();
      _builder.append("\t\t\t \t\t\t ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<!--\u4EE5\u4E0B\u662F\u9886\u6599\u5355-->");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdlabelbottom\">\u9886\u6599\u5355\u53F7:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdcontent\">");
      String _sid_1 = record.getSid();
      String _nullsafe_6 = Template.nullsafe(_sid_1);
      _builder.append(_nullsafe_6, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdlabelbottom\">\u4ED3\u4FDD\u5458:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdcontent\">");
      RCEmployee _operator = record.getOperator();
      String _entityName_3 = _operator.getEntityName();
      String _nullsafe_7 = Template.nullsafe(_entityName_3);
      _builder.append(_nullsafe_7, "			");
      _builder.append("</td> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdlabelbottom\">\u5907\u6CE8:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td class=\"tdcontent\">&nbsp;</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<table width=\"100%\" border=\"0\" align=\"center\" > ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<table  class=\"tableLL\">");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"25%\" >\u6750\u6599\u540D\u79F0</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"15%\" >\u89C4\u683C</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"18%\" >\u6279\u6B21</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"8%\" >\u6570\u91CF</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"8%\" >\u5355\u4F4D</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"12%\">\u5355\u4EF7\uFF08\u5143\uFF09</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th width=\"12%\">\u91D1\u989D\uFF08\u5143\uFF09</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</tr> ");
      _builder.newLine();
      _builder.newLine();
      {
        Collection<RCWorkItemStockRecordItem> _items = record.getItems();
        for(final RCWorkItemStockRecordItem item : _items) {
          _builder.append("\t\t\t");
          _builder.append("<tr>");
          _builder.newLine();
          _builder.append("\t\t\t");
          _builder.append("<td>");
          RCRecordItem _recordItem = item.getRecordItem();
          RCProductEntry _productEntry = _recordItem.getProductEntry();
          RCProductSpecification _productSpec = _productEntry.getProductSpec();
          String _entityName_4 = _productSpec.getEntityName();
          String _nullsafe_8 = Template.nullsafe(_entityName_4);
          _builder.append(_nullsafe_8, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("<td>");
          RCRecordItem _recordItem_1 = item.getRecordItem();
          RCProductEntry _productEntry_1 = _recordItem_1.getProductEntry();
          RCProductSpecification _productSpec_1 = _productEntry_1.getProductSpec();
          String _typeDesc = _productSpec_1.getTypeDesc();
          String _nullsafe_9 = Template.nullsafe(_typeDesc);
          _builder.append(_nullsafe_9, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("<td>");
          RCRecordItem _recordItem_2 = item.getRecordItem();
          RCProductEntry _productEntry_2 = _recordItem_2.getProductEntry();
          String _sid_2 = _productEntry_2.getSid();
          String _nullsafe_10 = Template.nullsafe(_sid_2);
          _builder.append(_nullsafe_10, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("<td>");
          RCRecordItem _recordItem_3 = item.getRecordItem();
          Integer _quantity = _recordItem_3.getQuantity();
          String _string = _quantity.toString();
          String _nullsafe_11 = Template.nullsafe(_string);
          _builder.append(_nullsafe_11, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("<td>");
          RCRecordItem _recordItem_4 = item.getRecordItem();
          RCProductEntry _productEntry_3 = _recordItem_4.getProductEntry();
          RCProductSpecification _productSpec_2 = _productEntry_3.getProductSpec();
          RCProduceSpecificationUnit _unit = _productSpec_2.getUnit();
          String _entityName_5 = _unit==null?(String)null:_unit.getEntityName();
          String _nullsafe_12 = Template.nullsafe(_entityName_5);
          _builder.append(_nullsafe_12, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("<td class=\"tdright\">");
          RCRecordItem _recordItem_5 = item.getRecordItem();
          RCProductEntry _productEntry_4 = _recordItem_5.getProductEntry();
          Double _price = _productEntry_4.getPrice();
          String _string_1 = _price.toString();
          String _nullsafe_13 = Template.nullsafe(_string_1);
          _builder.append(_nullsafe_13, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("<td class=\"tdright\">");
          RCRecordItem _recordItem_6 = item.getRecordItem();
          Double _totalAmount = _recordItem_6.getTotalAmount();
          String _string_2 = _totalAmount.toString();
          String _nullsafe_14 = Template.nullsafe(_string_2);
          _builder.append(_nullsafe_14, "			");
          _builder.append("</td> ");
          _builder.newLineIfNotEmpty();
          _builder.append("\t\t\t");
          _builder.append("</tr> ");
          _builder.newLine();
        }
      }
      _builder.append("\t\t\t");
      _builder.append("<tr>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th colspan=6>\u8D39\u7528\u5408\u8BA1</th> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<th class=\"tdright\">");
      Double _totalAmount_1 = record.getTotalAmount();
      String _string_3 = _totalAmount_1.toString();
      String _nullsafe_15 = Template.nullsafe(_string_3);
      _builder.append(_nullsafe_15, "			");
      _builder.append("</th> ");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("</tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<p>&nbsp;</p>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<!--\u4EE5\u4E0B\u662F\u786E\u8BA4-->");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<table width=\"100%\" border=\"0\" align=\"center\" > ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<tr> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"25%\" class=\"tdlabelbottom\">&nbsp</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"15%\"class=\"tdlabelbottom\">\u9662\u65B9\u7B7E\u5B57:</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"20%\" class=\"tdcontent\">&nbsp;</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"20%\" class=\"tdlabelbottom\">\u5DE5\u7A0B\u90E8\u8D1F\u8D23\u4EBA\uFF1A</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("<td width=\"20%\" class=\"tdcontent\">&nbsp</td> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</tr>  ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</table>");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</body> ");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("</html>");
      _builder.newLine();
      String _string_4 = _builder.toString();
      _xblockexpression = (_string_4);
    }
    return _xblockexpression;
  }
}
